### ISSUE TITLE
RuntimeError: output with shape [32, 2048, 2048] doesn't match the broadcast shape [1, 32, 2048, 2048]

### ISSUE THREAD

**Issue by bhkim94** [facebookresearch/3detr#1]
Hi,
Thank you for sharing your great work!

I'm running your pre-trained model to reproduce the results but I see the runtime error below.
The error seems about an input shape issue.
Do you have any suggestions for this?

This is the command that I put.
```
python main.py --dataset_name sunrgbd --nqueries 128 --test_ckpt weights/sunrgbd_masked_ep1080.pth --test_only --enc_type masked
```

This is the error that I have.
```
Traceback (most recent call last):
  File "main.py", line 427, in <module>
    launch_distributed(args)
  File "main.py", line 415, in launch_distributed
    main(local_rank=0, args=args)
  File "main.py", line 388, in main
    test_model(args, model, model_no_ddp, criterion, dataset_config, dataloaders)
  File "main.py", line 316, in test_model
    curr_iter,
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/user/Desktop/3detr/engine.py", line 179, in evaluate
    outputs = model(inputs)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/Desktop/3detr/models/model_3detr.py", line 306, in forward
    enc_xyz, enc_features, enc_inds = self.run_encoder(point_clouds)
  File "/home/user/Desktop/3detr/models/model_3detr.py", line 200, in run_encoder
    pre_enc_features, xyz=pre_enc_xyz
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/Desktop/3detr/models/transformer.py", line 190, in forward
    output = layer(output, src_mask=mask, src_key_padding_mask=src_key_padding_mask, pos=pos)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/Desktop/3detr/models/transformer.py", line 288, in forward
    return self.forward_pre(src, src_mask, src_key_padding_mask, pos, return_attn_weights)
  File "/home/user/Desktop/3detr/models/transformer.py", line 272, in forward_pre
    key_padding_mask=src_key_padding_mask)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 819, in forward
    attn_mask=attn_mask)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/nn/functional.py", line 3362, in multi_head_attention_forward
    attn_output_weights += attn_mask
RuntimeError: output with shape [32, 2048, 2048] doesn't match the broadcast shape [1, 32, 2048, 2048]
```

**Comment by imisra** [comment]
Hi @bhkim94 

I am not able to reproduce this issue. I just tried it by git cloning and running the exact same command. What version of PyTorch are you using?

The code was developed and tested with PyTorch 1.4.0

**Comment by bhkim94** [comment]
Hi @imisra

Thanks for replying.
I installed PyTorch 1.4.0. by following the "installation" section in README.

**Comment by imisra** [comment]
I think I know what's going on here.
In 1.4.0, a 3D attention mask isn't handled properly.
Can you see comment out `attn_mask = attn_mask.unsqueeze(0)` in L3361 of `torch/nn/functional.py`?
I think this is causing the 3D attention mask to become 4D.

Latest PyTorch versions do this correctly - https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L5015

**Comment by bhkim94** [comment]
Thanks. That solves the issue!

I'm currently evaluating the pretrained weight of 3DETR-m with 1080 epochs, expecting 59.1 in AP25 and 30.3 in AP50.
But the result seems not matching to the numbers in README. Below is the result that I reproduced.
Would it be due to the code changes in removing unsqueeze(0)?
```
====================
Test model; Metrics mAP0.25, mAP0.50: 29.20, 5.40
AR0.25, AR0.50: 49.92, 13.77
-----
IOU Thresh=0.25
bed Average Precision: 50.15
table Average Precision: 26.78
sofa Average Precision: 18.68
chair Average Precision: 47.00
toilet Average Precision: 73.00
desk Average Precision: 11.66
dresser Average Precision: 7.71
night_stand Average Precision: 11.15
bookshelf Average Precision: 11.25
bathtub Average Precision: 34.62
bed Recall: 65.93
table Recall: 56.40
sofa Recall: 52.11
chair Recall: 57.78
toilet Recall: 82.78
desk Recall: 48.40
dresser Recall: 26.85
night_stand Recall: 28.35
bookshelf Recall: 34.45
bathtub Recall: 46.15
-----
IOU Thresh=0.5
bed Average Precision: 6.49
table Average Precision: 1.03
sofa Average Precision: 1.54
chair Average Precision: 6.21
toilet Average Precision: 29.10
desk Average Precision: 0.39
dresser Average Precision: 0.87
night_stand Average Precision: 3.19
bookshelf Average Precision: 0.48
bathtub Average Precision: 4.67
bed Recall: 14.55
table Recall: 9.08
sofa Recall: 12.36
chair Recall: 18.24
toilet Recall: 41.72
desk Recall: 6.69
dresser Recall: 7.87
night_stand Recall: 8.66
bookshelf Recall: 5.02
bathtub Recall: 13.46
====================
```

**Comment by imisra** [comment]
This is surprising. Can you check the performance for 3DETR (no masking)? That won't depend on the unsqueeze() fix.

**Comment by bhkim94** [comment]
It seems the non-masked version reproduces the result well.
Below is the result that I reproduced (3DETR, SUNRGBD, 1080 epochs).
```
====================
Test model; Metrics mAP0.25, mAP0.50: 57.41, 29.76
AR0.25, AR0.50: 78.87, 45.61
-----
IOU Thresh=0.25
bed Average Precision: 85.16
table Average Precision: 48.73
sofa Average Precision: 57.74
chair Average Precision: 67.92
toilet Average Precision: 90.09
desk Average Precision: 27.63
dresser Average Precision: 30.60
night_stand Average Precision: 59.07
bookshelf Average Precision: 30.84
bathtub Average Precision: 76.34
bed Recall: 92.45
table Recall: 77.42
sofa Recall: 82.00
chair Recall: 76.98
toilet Recall: 94.70
desk Recall: 70.68
dresser Recall: 73.15
night_stand Recall: 81.89
bookshelf Recall: 54.85
bathtub Recall: 84.62
-----
IOU Thresh=0.5
bed Average Precision: 52.53
table Average Precision: 18.53
sofa Average Precision: 35.78
chair Average Precision: 39.33
toilet Average Precision: 63.73
desk Average Precision: 5.84
dresser Average Precision: 15.52
night_stand Average Precision: 26.77
bookshelf Average Precision: 3.73
bathtub Average Precision: 35.83
bed Recall: 61.14
table Recall: 38.69
sofa Recall: 53.21
chair Recall: 50.94
toilet Recall: 71.52
desk Recall: 28.43
dresser Recall: 43.06
night_stand Recall: 49.61
bookshelf Recall: 13.38
bathtub Recall: 46.15
====================
```

**Comment by imisra** [comment]
I am able to reproduce the 3DETR-m SUNRGBD 1080 epoch results from the released checkpoint

```
====================
Test model; Metrics mAP0.25, mAP0.50: 59.05, 30.28
AR0.25, AR0.50: 80.35, 46.00
-----
IOU Thresh=0.25
bed Average Precision: 83.23
table Average Precision: 48.40
sofa Average Precision: 63.98
chair Average Precision: 71.41
toilet Average Precision: 90.18
desk Average Precision: 31.37
dresser Average Precision: 30.80
night_stand Average Precision: 62.24
bookshelf Average Precision: 31.38
bathtub Average Precision: 77.54
bed Recall: 91.34
table Recall: 80.04
sofa Recall: 86.70
chair Recall: 79.84
toilet Recall: 94.04
desk Recall: 73.34
dresser Recall: 71.30
night_stand Recall: 81.50
bookshelf Recall: 58.86
bathtub Recall: 86.54
-----
IOU Thresh=0.5
bed Average Precision: 49.30
table Average Precision: 18.30
sofa Average Precision: 42.46
chair Average Precision: 43.77
toilet Average Precision: 66.07
desk Average Precision: 7.86
dresser Average Precision: 14.03
night_stand Average Precision: 28.22
bookshelf Average Precision: 6.38
bathtub Average Precision: 26.45
bed Recall: 61.14
table Recall: 41.06
sofa Recall: 56.65
chair Recall: 55.66
toilet Recall: 71.52
desk Recall: 29.71
dresser Recall: 39.81
night_stand Recall: 47.64
bookshelf Recall: 16.39
bathtub Recall: 40.38
====================
```

I'll try with a fresh conda environment and get back to you.

**Comment by imisra** [comment]
It's a bug in the way `bool` masks are handled. Can you try the following lines in the nn/functional.py file (L3361)

```python
if attn_mask is not None:
        #attn_mask = attn_mask.unsqueeze(0)
        if attn_mask.dtype == torch.bool:
            attn_output_weights.masked_fill_(attn_mask, float('-inf'))
        else:
            attn_output_weights += attn_mask
```

**Comment by imisra** [comment]
It seems PyTorch 1.9.1 can repro the results. You can just use that directly

**Comment by bhkim94** [comment]
> It's a bug in the way bool masks are handled. Can you try the following lines in the nn/functional.py file (L3361)

This solves the issue of the masked model!
Below is the reproduced result.
```
====================
Test model; Metrics mAP0.25, mAP0.50: 58.34, 30.69
AR0.25, AR0.50: 80.24, 47.13
-----
IOU Thresh=0.25
bed Average Precision: 83.20
table Average Precision: 48.57
sofa Average Precision: 64.36
chair Average Precision: 71.50
toilet Average Precision: 91.92
desk Average Precision: 32.65
dresser Average Precision: 28.90
night_stand Average Precision: 60.06
bookshelf Average Precision: 27.92
bathtub Average Precision: 74.27
bed Recall: 91.16
table Recall: 79.59
sofa Recall: 86.70
chair Recall: 79.92
toilet Recall: 95.36
desk Recall: 74.13
dresser Recall: 71.30
night_stand Recall: 83.07
bookshelf Recall: 56.52
bathtub Recall: 84.62
-----
IOU Thresh=0.5
bed Average Precision: 48.09
table Average Precision: 18.59
sofa Average Precision: 43.22
chair Average Precision: 44.74
toilet Average Precision: 67.23
desk Average Precision: 7.32
dresser Average Precision: 12.23
night_stand Average Precision: 33.82
bookshelf Average Precision: 5.53
bathtub Average Precision: 26.10
bed Recall: 59.67
table Recall: 42.00
sofa Recall: 59.31
chair Recall: 56.28
toilet Recall: 72.85
desk Recall: 29.81
dresser Recall: 37.96
night_stand Recall: 54.72
bookshelf Recall: 16.39
bathtub Recall: 42.31
====================
```

> It seems PyTorch 1.9.0 can repro the results. You can just use that directly

I installed PyTorch 1.9.0 but it gives an error below.
```
Traceback (most recent call last):
  File "/home/user/Desktop/3detr/third_party/pointnet2/pointnet2_utils.py", line 23, in <module>
    import pointnet2._ext as _ext
ImportError: /home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/pointnet2-0.0.0-py3.6-linux-x86_64.egg/pointnet2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from models import build_model
  File "/home/user/Desktop/3detr/models/__init__.py", line 2, in <module>
    from .model_3detr import build_3detr
  File "/home/user/Desktop/3detr/models/model_3detr.py", line 8, in <module>
    from third_party.pointnet2.pointnet2_modules import PointnetSAModuleVotes
  File "/home/user/Desktop/3detr/third_party/pointnet2/pointnet2_modules.py", line 18, in <module>
    import pointnet2_utils
  File "/home/user/Desktop/3detr/third_party/pointnet2/pointnet2_utils.py", line 27, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
```

**Comment by rohitgirdhar** [comment]
Can you try to recompile pointnet after installing pytorch 1.9?

**Comment by bhkim94** [comment]
Recompiling pointnet with 1.9.0 returns the error below
```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1672, in _run_ninja_build
    env=env)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    'build_ext': BuildExtension
  File "/home/user/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/user/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/user/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 539, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1360, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/user/anaconda3/envs/3detr/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by rohitgirdhar** [comment]
Which CUDA version are you using with pytorch 1.9? Can you try with the CUDA 10.2 version?

**Comment by bhkim94** [comment]
I tried with pytorch 1.9 and CUDA 10.2 and that works well.
The CUDA version is the reason.

Thanks for helping! @imisra @rohitgirdhar
