### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError

### ISSUE THREAD

**Issue by liudaxia96** [facebookresearch/3detr#24]
Sorry, I accidentally closed my question. Have you tried to use Python 3.8?
Traceback (most recent call last):
  File "/usr/local/python38/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/python38/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
^CTraceback (most recent call last):
  File "/home/lab30201/sdb/lwb/3detr-main/main.py", line 430, in <module>
    launch_distributed(args)
  File "/home/lab30201/sdb/lwb/3detr-main/main.py", line 418, in launch_distributed
    main(local_rank=0, args=args)
  File "/home/lab30201/sdb/lwb/3detr-main/main.py", line 403, in main
    do_train(
  File "/home/lab30201/sdb/lwb/3detr-main/main.py", line 179, in do_train
    aps = train_one_epoch(
  File "/home/lab30201/sdb/lwb/3detr-main/engine.py", line 74, in train_one_epoch
    for batch_idx, batch_data_label in enumerate(dataset_loader):
  File "/usr/local/python38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/python38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/usr/local/python38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/python38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/local/python38/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/usr/local/python38/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/local/python38/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/usr/local/python38/lib/python3.8/multiprocessing/connection.py", line 930, in wait
    ready = selector.select(timeout)
  File "/usr/local/python38/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)

**Comment by imisra** [comment]
I have not tried Python 3.8. Can you just try evaluating the checkpoint dumped at this epoch since this error occurred during evaluation? That will help narrow it down.

**Comment by liudaxia96** [comment]
CUDA Version: 11.1

**Comment by liudaxia96** [comment]
> I have not tried Python 3.8. Can you just try evaluating the checkpoint dumped at this epoch since this error occurred during evaluation? That will help narrow it down.

What reason did you say that might be caused by Python3.8？

**Comment by imisra** [comment]
Since I haven't seen this error, I was trying to rule out issues due to different versions of Python

**Comment by liudaxia96** [comment]
My Environment:

OS: Ubuntu 18.04
GPU: GeForce GTX 1080
CUDA Version 11.1
pytorch Version 1.7.1
python 3.8.1

**Comment by liudaxia96** [comment]
> OK, I'm trying to solve this problem. If not, try Python3.6
